AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to set up SSM access, including VPC endpoints, IAM roles, and security group rules'

Parameters:
  VpcId:
    Type: List<AWS::EC2::VPC::Id>
    Description: The VPC ID where the resources will be created

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs where the SSM endpoints will be created

  SecurityGroupId:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: The Security Group ID to modify for SSM access

Resources:
  # SSM VPC Endpoints
  SSMEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ssm'
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      SubnetIds: !Ref SubnetIds
      SecurityGroupIds: 
        - !Ref SecurityGroupId

  SSMMessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ssmmessages'
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      SubnetIds: !Ref SubnetIds
      SecurityGroupIds: 
        - !Ref SecurityGroupId

  EC2MessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ec2messages'
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      SubnetIds: !Ref SubnetIds
      SecurityGroupIds: 
        - !Ref SecurityGroupId

  # IAM Role for SSM
  SSMIAMRole:
    Type: AWS::IAM::Role
    Properties:
      Name: SSMAccessRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  # Security Group Rule
  SSMSecurityGroupRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroupId
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      SourceSecurityGroupId: !Ref SecurityGroupId

  RDPSecurityGroupRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroupId
      IpProtocol: tcp
      FromPort: 3389
      ToPort: 3389
      SourceSecurityGroupId: !Ref SecurityGroupId

Outputs:
  SSMIAMRoleArn:
    Description: ARN of the IAM Role created for SSM
    Value: !GetAtt SSMIAMRole.Arn

